---
- hosts: nginx
  tasks:
    - name: set the hostname
      hostname:
        name: "{{hostname}}"
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
    - name: nginx configuration file
      template:
        src: ubuntu/nginx/nginx.conf.j2
        dest: /etc/nginx/sites-available/{{nginx_site_name}}.conf
        owner: root
        group: root
        mode: '0644'
    - name: create ssl directory
      file:
        path: /etc/nginx/ssl
        state: directory
    - name: create nginxconfig.io directory
      file:
        path: /etc/nginx/nginxconfig.io
        state: directory
    - name: ssl certificate
      template:
        src: ubuntu/nginx/ssl.crt.j2
        dest: /etc/nginx/ssl/ssl.crt
        owner: root
        group: root
        mode: '0644'
    - name: private key file
      template:
        src: ubuntu/nginx/private.key.j2
        dest: /etc/nginx/ssl/private.key
        owner: root
        group: root
        mode: '0644'
    - name: proxy configuration settings
      template:
        src: ubuntu/nginx/proxy.conf.j2
        dest: /etc/nginx/nginxconfig.io/proxy.conf
        owner: root
        group: root
        mode: '0644'
    - name: general configuration settings
      template:
        src: ubuntu/nginx/general.conf.j2
        dest: /etc/nginx/nginxconfig.io/general.conf
        owner: root
        group: root
        mode: '0644'
    - name: Remove existing symbolic link
      file:
        path: /etc/nginx/sites-enabled/{{nginx_site_name}}.conf
        state: absent
    - name: Enable site by creating symbolic link
      file:
        src: /etc/nginx/sites-available/{{nginx_site_name}}.conf
        dest: /etc/nginx/sites-enabled/{{nginx_site_name}}.conf
        state: hard
    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
